package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"strings"

	"github.com/cloudwego/eino-ext/components/model/openai"
	"github.com/cloudwego/eino/compose"
	"github.com/cloudwego/eino/schema"
	"github.com/joho/godotenv"
)

// ตัวอย่าง Graph ที่ใช้ LLM จริง
func main() {
	// Load environment
	err := godotenv.Load()
	if err != nil {
		log.Fatal("Error loading .env file")
	}

	ctx := context.Background()
	apiKey := os.Getenv("OPENROUTER_API_KEY")
	if apiKey == "" {
		fmt.Println("Please set OPENROUTER_API_KEY environment variable")
		return
	}

	// สร้าง model configuration
	config := &openai.ChatModelConfig{
		APIKey:  apiKey,
		BaseURL: "https://openrouter.ai/api/v1",
		Model:   "openai/gpt-3.5-turbo",
	}

	model, err := openai.NewChatModel(ctx, config)
	if err != nil {
		fmt.Printf("Error creating model: %v\n", err)
		return
	}

	// === ตัวอย่าง LLM Pipeline Graph ===
	fmt.Println("=== LLM Pipeline Graph ===")
	runLLMPipeline(ctx, model)

	// === ตัวอย่าง Multi-Step LLM Processing ===
	fmt.Println("\n=== Multi-Step LLM Processing ===")
	runMultiStepLLM(ctx, model)
}

// LLM Pipeline Graph
func runLLMPipeline(ctx context.Context, model *openai.ChatModel) {
	graph := compose.NewGraph[string, string]()

	// Input preprocessor
	preprocessor := compose.InvokableLambda(func(ctx context.Context, input string) ([]*schema.Message, error) {
		// เตรียม messages สำหรับ LLM
		messages := []*schema.Message{
			schema.SystemMessage("คุณเป็น AI assistant ที่ช่วยตอบคำถามและให้คำแนะนำเป็นภาษาไทย"),
			schema.UserMessage(input),
		}
		fmt.Printf("🔧 Preprocessor: Prepared %d messages for LLM\n", len(messages))
		return messages, nil
	})

	// LLM processor - ใช้ model จริง
	llmProcessor := compose.InvokableLambda(func(ctx context.Context, messages []*schema.Message) (string, error) {
		fmt.Printf("🤖 LLM: Processing request...\n")
		
		response, err := model.Generate(ctx, messages)
		if err != nil {
			return "", fmt.Errorf("LLM error: %w", err)
		}
		
		result := response.Content
		fmt.Printf("🤖 LLM Response: %s\n", result)
		return result, nil
	})

	// Postprocessor
	postprocessor := compose.InvokableLambda(func(ctx context.Context, input string) (string, error) {
		// ปรับแต่งและเพิ่ม metadata
		processed := fmt.Sprintf("✨ AI Response: %s\n\n📝 Note: This response was generated by AI", input)
		fmt.Printf("🎯 Postprocessor: Added metadata and formatting\n")
		return processed, nil
	})

	// เพิ่ม nodes
	graph.AddLambdaNode("preprocessor", preprocessor)
	graph.AddLambdaNode("llm", llmProcessor)
	graph.AddLambdaNode("postprocessor", postprocessor)

	// เชื่อม edges
	graph.AddEdge(compose.START, "preprocessor")
	graph.AddEdge("preprocessor", "llm")
	graph.AddEdge("llm", "postprocessor")
	graph.AddEdge("postprocessor", compose.END)

	// Compile และทดสอบ
	runnable, err := graph.Compile(ctx)
	if err != nil {
		fmt.Printf("Error compiling LLM pipeline: %v\n", err)
		return
	}

	testQuestions := []string{
		"อธิบาย Eino Graph ให้ฟังหน่อย",
		"วิธีการสร้าง parallel processing ใน Go",
	}

	for i, question := range testQuestions {
		fmt.Printf("\n--- Question %d ---\n", i+1)
		fmt.Printf("Input: %s\n", question)

		result, err := runnable.Invoke(ctx, question)
		if err != nil {
			fmt.Printf("Error: %v\n", err)
			continue
		}

		fmt.Printf("\n%s\n", result)
	}
}

// Multi-Step LLM Processing
func runMultiStepLLM(ctx context.Context, model *openai.ChatModel) {
	graph := compose.NewGraph[string, string]()

	// Step 1: Analyze user intent
	intentAnalyzer := compose.InvokableLambda(func(ctx context.Context, input string) (string, error) {
		messages := []*schema.Message{
			schema.SystemMessage("วิเคราะห์ intent ของผู้ใช้และจำแนกเป็น: QUESTION, REQUEST, COMMAND, CASUAL"),
			schema.UserMessage(fmt.Sprintf("Input: %s\n\nIntent:", input)),
		}

		response, err := model.Generate(ctx, messages)
		if err != nil {
			return "", err
		}

		intent := strings.TrimSpace(response.Content)
		result := fmt.Sprintf("%s|%s", intent, input)
		fmt.Printf("🎯 Intent Analyzer: '%s' -> Intent: %s\n", input, intent)
		return result, nil
	})

	// Step 2: Context-aware response generator
	responseGenerator := compose.InvokableLambda(func(ctx context.Context, input string) (string, error) {
		parts := strings.SplitN(input, "|", 2)
		if len(parts) != 2 {
			return input, nil
		}

		intent := parts[0]
		userInput := parts[1]

		// สร้าง context-aware prompt ตาม intent
		var systemPrompt string
		switch {
		case strings.Contains(intent, "QUESTION"):
			systemPrompt = "คุณเป็นครูที่เชี่ยวชาญ ตอบคำถามอย่างละเอียดและให้ตัวอย่าง"
		case strings.Contains(intent, "REQUEST"):
			systemPrompt = "คุณเป็นผู้ช่วยที่พร้อมช่วยเหลือ ให้คำแนะนำที่เป็นประโยชน์"
		case strings.Contains(intent, "COMMAND"):
			systemPrompt = "คุณเป็นผู้เชี่ยวชาญเทคนิค ให้คำสั่งและขั้นตอนที่ชัดเจน"
		default:
			systemPrompt = "คุณเป็น AI assistant ที่เป็นมิตรและช่วยเหลือ"
		}

		messages := []*schema.Message{
			schema.SystemMessage(systemPrompt),
			schema.UserMessage(userInput),
		}

		fmt.Printf("🤖 Response Generator: Using %s strategy\n", intent)
		response, err := model.Generate(ctx, messages)
		if err != nil {
			return "", err
		}

		result := fmt.Sprintf("[%s] %s", intent, response.Content)
		return result, nil
	})

	// Step 3: Quality checker
	qualityChecker := compose.InvokableLambda(func(ctx context.Context, input string) (string, error) {
		// ตรวจสอบคุณภาพของ response
		if len(input) < 50 {
			enhanced := input + "\n\n💡 Tip: For more detailed information, please ask more specific questions."
			fmt.Printf("🔍 Quality Checker: Enhanced short response\n")
			return enhanced, nil
		}

		fmt.Printf("🔍 Quality Checker: Response quality is good\n")
		return input, nil
	})

	// เพิ่ม nodes
	graph.AddLambdaNode("intent_analyzer", intentAnalyzer)
	graph.AddLambdaNode("response_generator", responseGenerator)
	graph.AddLambdaNode("quality_checker", qualityChecker)

	// เชื่อม edges
	graph.AddEdge(compose.START, "intent_analyzer")
	graph.AddEdge("intent_analyzer", "response_generator")
	graph.AddEdge("response_generator", "quality_checker")
	graph.AddEdge("quality_checker", compose.END)

	// Compile และทดสอบ
	runnable, err := graph.Compile(ctx)
	if err != nil {
		fmt.Printf("Error compiling multi-step LLM: %v\n", err)
		return
	}

	testInputs := []string{
		"Go คืออะไร?",
		"ช่วยเขียน function สำหรับ sort array ได้ไหม",
		"สร้าง Docker container",
		"สวัสดี",
	}

	for i, input := range testInputs {
		fmt.Printf("\n--- Test %d ---\n", i+1)
		fmt.Printf("Input: %s\n", input)

		result, err := runnable.Invoke(ctx, input)
		if err != nil {
			fmt.Printf("Error: %v\n", err)
			continue
		}

		fmt.Printf("\nResult:\n%s\n", result)
		fmt.Println(strings.Repeat("-", 80))
	}
}